### ISSUE TITLE
mark the old package as deprecated

### ISSUE THREAD

**Issue by spipu** [fabpot/local-php-security-checker#16]
Hi @fabpot 

is it possible to mark the previous old repo https://github.com/sensiolabs/security-checker as deprecated in the composer.json info, and to suggest this new one instead ?

thanks :)

Laurent

**Comment by pvsaintpe** [comment]
@spipu I think, this is a good idea!

**Comment by spipu** [comment]
i just read a bit more about all this, this repo is not a suggest replacement because it is not a composer package, it is a CLI tool.

I think we can just mark the old one as deprecated, that's all. 

Now, security checker is not any more a project package, but a global cli tool.

**Comment by SpacePossum** [comment]
The [composer schema ](https://getcomposer.org/doc/04-schema.md) does not have that option. The package has been deprecated on [packagist](https://packagist.org/packages/sensiolabs/security-checker) with replacement instructions.

One minor thing that can be done is updating `composer.json` to mark it as `abandoned`, however since the project is archived github doesn't allow PR'ing it ;)
example patch: https://github.com/SpacePossum/security-checker/pull/1/files

**Comment by fabpot** [comment]
The package is already abandoned on Packagist, that should be enough?

**Comment by spipu** [comment]
Yes, sorry, you are right, ti was just that i did not see the warning from composer during my last update

**Comment by InstanceOfMichael** [comment]
Can this also be released as a composer package? I'd much rather run `./vendor/bin/local-php-security-checker --format=json` than do a global system install for this kind of thing. Also it would be good for discoverability on packagist.
